### ISSUE TITLE
DNS Leak

### ISSUE THREAD

**Issue by divin** [DedBash/WireGuard-VPN-on-Fritz-Box#2]
Hi, so I followed your tutorial but it seems there are still some problems. When checking the connection with the tool provided by Mullvad, some checks fail. I'm not very good with networks but it seems the IPv6 is leaking which is why the first checks fail. The IPv4 is from Mullvad. As for the DNS, I'm not sure what I need to adjust to make it work. I guess I need to somehow get some DNS addresses from Mullvad and assign them on my Fritz!box. Have you solved this problem on your end? And if so, how?

<img width="241" alt="Screenshot 2024-05-22 at 21 02 08 2" src="https://github.com/DedBash/WireGuard-VPN-on-Fritz-Box/assets/71128266/c5267dfd-f3c8-427c-9cc3-f5cf45fb0294">
<img width="430" alt="Screenshot 2024-05-22 at 21 01 50 2" src="https://github.com/DedBash/WireGuard-VPN-on-Fritz-Box/assets/71128266/0b92f8e2-632a-4020-ad75-9004f7e5f085">

**Comment by DedBash** [comment]
Hi @divin,
For the part with the DNS leak stuff seems to come from Mullvad itself as I also get this with their client on pc and I'm sure Mullvad is doing something there as I always have the quad9 dns server set up myself (In windwos and the Fritzbox)
![image](https://github.com/DedBash/WireGuard-VPN-on-Fritz-Box/assets/79027536/04a64f50-579a-43ec-96a3-1de510331cd6)

But there is a DNS server in the Wireguard config, you are welcome to try to use it
![image](https://github.com/DedBash/WireGuard-VPN-on-Fritz-Box/assets/79027536/60be348d-3c5a-4e04-82bf-c91cdab2fdc6)

Unfortunately I can't help you with IPv6 because I don't get one from my provider, but in the Fritzbox VPN setup there should be a point as with IPv6 which devices go via the IPv6 vpn

**Comment by divin** [comment]
@DedBash thanks for the quick reply, the trick with the DNS server in the config is neat, there is also [this repository](https://github.com/mullvad/dns-blocklists#custom-dns-entries-for-use-with-our-vpn-service) which contains more DNS addresses. I have now solved the problem by disabling IPv6 on my FritzBox. As I said, I'm not that good with networking stuff, so I'm not sure if I'll ever need this 😄 

<img width="1376" alt="Screenshot 2024-05-23 at 20 10 52" src="https://github.com/DedBash/WireGuard-VPN-on-Fritz-Box/assets/71128266/37388630-ad43-41b1-917e-a61f7cd78788">
